### ISSUE TITLE
what is "Too many delays" ??

### ISSUE THREAD

**Issue by ghost** [respeaker/pocketsphinx-data#1]
followed these instructions.. and without the ENV path all i see if
INFO:mic:Detected alexa
INFO:mic:Detected alexa 
INFO:mic:Detected respeaker
INFO:mic:Detected alexa

but with the ENV path set, I can add new word which get detected but it now fills up with a message about "Too many delays"

INFO:mic:Start detecting
INFO:mic:Too many delays, 10 in queue
INFO:mic:Too many delays, 13 in queue
INFO:mic:Too many delays, 15 in queue
INFO:mic:Too many delays, 14 in queue
INFO:mic:Too many delays, 16 in queue
INFO:mic:Too many delays, 15 in queue
INFO:mic:Too many delays, 17 in queue
INFO:mic:Too many delays, 16 in queue
INFO:mic:Too many delays, 18 in queue
INFO:mic:Too many delays, 17 in queue
INFO:mic:Too many delays, 19 in queue
INFO:mic:Too many delays, 18 in queue
INFO:mic:Too many delays, 20 in queue
INFO:mic:Too many delays, 22 in queue
INFO:mic:Detected samantha 
INFO:mic:Too many delays, 24 in queue
INFO:mic:Too many delays, 23 in queue
INFO:mic:Too many delays, 22 in queue
INFO:mic:Too many delays, 21 in queue
INFO:mic:Too many delays, 20 in queue
INFO:mic:Too many delays, 19 in queue
INFO:mic:Too many delays, 18 in queue
INFO:mic:Too many delays, 17 in queue
INFO:mic:Too many delays, 16 in queue
INFO:mic:Too many delays, 15 in queue
INFO:mic:Too many delays, 14 in queue
INFO:mic:Too many delays, 13 in queue
INFO:mic:Too many delays, 12 in queue
INFO:mic:Too many delays, 11 in queue
INFO:mic:Too many delays, 10 in queue
INFO:mic:Too many delays, 9 in queue
INFO:mic:Too many delays, 8 in queue
INFO:mic:Too many delays, 7 in queue
INFO:mic:Too many delays, 6 in queue
INFO:mic:Too many delays, 5 in queue
INFO:mic:Too many delays, 5 in queue

whats happening here?? I have checked that there is no blank links in the keyword.txt file.. just the 3 i have entered

**Comment by xiongyihui** [comment]
You can ignore the message. It indicates how many unhandled audio in the queue.

**Comment by ghost** [comment]
thanks
